### ISSUE TITLE
Suggestion: Add "Done" and "Host" column in the Checklist

### ISSUE THREAD

**Issue by Regala** [GovTech-CSG/Autowasp#6]
Hi folks! First off awesome job with this extension, it solves a gap in the pentesters flow and it's really well documented. 

I have a couple of suggestions, which I'd love to be added. The first is adding a "Done" column, equal to the "To Exclude". Basically this would allow us to keep track of what tests have been done and complement the excluded tests very nicely.

The second one would be adding a host column. I assume this is much more tricky and probably not for everyone. But personally, when testing a target I have multiple targets/hosts. As such, for me to cover everything I need to distinguish the tests done in one host for another. With that host tab, I could make sure that all the tests were done and covered in all of the scope. I'm not sure the best way to implement this - e.g. duplicating the checklist items for every host in scope to test, or being able to duplicate only some items, or simply making the host column a text input where we could manually write the targets we tested.

Very crude mockup:

![suggestion_ (1)](https://user-images.githubusercontent.com/1380527/110778987-f2605880-825a-11eb-9570-a7093446162d.png)

Thanks and keep up the good work!

**Comment by imthomas93** [comment]
Hi @Regala.

Thank you for using and your feedback for Autowasp. For the first feature request, I agree that we can do better by adding the Done column into the testing checklist tool for a better user experience. This will be in our product pipeline for upcoming release. 

For your second feedback, yes, adding a host column could be tricky as a pen-tester might use be testing an application with multiple different endpoint. Do let us discuss internally and see how can we implement this to make the feature better.

Once again! Thank you for your support!

**Comment by imthomas93** [comment]
Hi @Regala,

Just an update, we have added the "completed" checkbox in our minor updates. In future, we are exploring using this checkbox to populate information - "No vulnerability exception noted" when populating the checklist into our excel report.

Thanks for your support in using Autowasp 👍 

@imthomas93

**Comment by Regala** [comment]
Awesome!! Cheers!
