### ISSUE TITLE
Autowasp bug in Burp Pro - v2021.4 (Early)

### ISSUE THREAD

**Issue by vay3t** [GovTech-CSG/Autowasp#9]
I have managed to identify a bug in the Autowasp menu. As you can see in the image, the buttons and information displayed by the plugin are not clearly visible.

![image](https://user-images.githubusercontent.com/6080369/113367986-e6d0f080-9333-11eb-8c7c-8fe6f6d9adf4.png)

**Comment by rewardone** [comment]
This also happens in 2021.3.1 if the width of Burp Suite is not set appropriately. The UI in the first row will wrap.

**Comment by imthomas93** [comment]
Hi @rewardone and @vay3t,

We have done a minor UI updates in wrapping the first row. Pleas find our release over here - https://github.com/GovTech-CSG/Autowasp/releases/tag/v1.0.1

Thank you for feedback and support in using Autowasp 👍 

@imthomas93

**Comment by vay3t** [comment]
Fixed! 
![image](https://user-images.githubusercontent.com/6080369/114580463-df231d00-9c4c-11eb-830f-27687f399728.png)
